### ISSUE TITLE
Eigen include path on newlik branch

### ISSUE THREAD

**Issue by psathyrella** [BioPP/bpp-phyl#26]
This could be somewhat specific to my setup, but at least when eigen is installed with apt-get (libeigen3-dev) on ubuntu 16.04, the bpp-phyl compilation looks for headers under e.g. `Eigen/Core`, whereas the system has them installed under the additional `eigen3` subdir (e.g. `/usr/include/eigen3/Eigen/Core`). I hackily/temporarily fixed this by editing the actual include line in DataFlowCWise.h and DataFlowNumeric.h, is there a more recommended way, or am I doing something else wrong?

**edit to add:**

My understanding is also that, being a header library, eigen shouldn't appear in the linker commands [here](https://github.com/BioPP/bpp-phyl/blob/newlik/src/CMakeLists.txt#L251) and [here](https://github.com/BioPP/bpp-phyl/blob/newlik/src/CMakeLists.txt#L265). Removing it fixes an ld crash.

Also, [this include](https://github.com/BioPP/bpp-phyl/blob/newlik/test/new_likelihood.cpp#L48) seems to need to be renamed to `LikelihoodCalculationSingleProcess.h`.

**Comment by lgueguen** [comment]
Dear, 

first, all those classes in newlik branch are under rather quick and unstable development, so I would not  advise you to look into those for the next few weeks (not more I hope).

About the link problem in the CMakeLists.txt files, I look at it, thanks for the note.

Cheers,
Laurent

**Comment by lereldarion** [comment]
Hello,

I've investigated the problem with CMake. Short version : your Eigen version is a bit old. Long version below.

CMake has introduced a _target system_ to replace the old paradigm of `include_directories(${<lib>_INCLUDE_DIRS})` after a `find_package(<lib>)`. In the target system, a library would define one or more CMake _targets_, and attach properties to them like include paths, link flags and so on. Then a single `target_link_libraries(prog <target>)` would extract all the properties from the target and use them where needed to compile `prog`.

Sadly, due to a lack on emphasis on this new system in official documentation, and the amount of old tutorials found by google on the old style, adoption of this _Modern CMake_ style is slow. See [there](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/) for a good tutorial on the new style.

In our case, Bio++ (even master) now uses _Modern CMake_ and define targets ; a general documentation of that can be found [there](https://github.com/BioPP/bpp-core/tree/master/cmake). The `newlik` branch adds a dependency to Eigen, and expects Eigen to use Modern Cmake as well and define a `Eigen3::Eigen` target, as documented [here](https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html). Eigen being a header-only library, the Eigen3::Eigen target *only defines an include path*, and can be used in `target_link_libraries` as discussed before : this is not an error.

However, it turns out that Eigen only uses targets since [Eigen 3.3.1](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.1). On ubuntu 16.04, Eigen uses the 3.3-beta2 version, which uses the old style cmake only, thus our CMake breaks because the expected target does not exists. It does not add the `eigen3/` prefix, and probably tries to link to a library named `libEigen3::Eigen` as a fallback solution.

Possible solutions to fix this problem in general:
1. Only support Eigen above 3.3.1
2. Use a locally installed Eigen of version above 3.3.1, and tell CMake to look there using CMAKE_PREFIX_PATH.
3. Modify Bio++ Cmake to work with target-less versions of Eigen, by either adding the include path manually, or creating an Eigen target ourselves.

@psathyrella : the simplest and fastest solution for you is to use solution 2, or manually fix Bio++ code / cmake like you have already done.

**Comment by psathyrella** [comment]
Great, thanks for the detailed description. I ended up needing to install the latest Eigen source since bppsuite requires 3.3, and we're all used to ubuntu packages being ancient anyway, so it works out.

Is there a better way to get the multiple models functionality (different model for each site, for me) than to use the newlik branch? fwiw I have it working now, and it seems to be doing what I expect it to, but if there's a more stable version that's always less likely to cause tears in my future.

**Comment by lgueguen** [comment]
No, this is fine that you use newlik. The unstable part is on the way the likelihoods are computed, but if you just use bppsuite it should be transparent for you (hopefully, getting more and more efficient). All the I/O, modeling description and definition is quite stable now.

Cheers,
Laurent
